### ISSUE TITLE
Pin code 0369 passes

### ISSUE THREAD

**Issue by LeoJHarris** [havardt/PasswordValidator#22]
The integers 0369 passes the sequence validation check when it should not.

```csharp
private PasswordValidator getPinCodeSequenceCheckValidator => _sequenceCheckValidator ??= new PasswordValidator(CheckTypes.NumberSequence)
    {
        NumberSequenceLength = 2
    };
```

**Comment by havardt** [comment]
Thanks for creating an issue. The reason 0369 is valid is because it checks incrementing and decrementing number sequences such as 123 and 321 rather than just checking for any number sequence. 

I realise the name of the check makes this confusing and I will consider creating a new check with a better name.

Closing the issue for now.

**Comment by LeoJHarris** [comment]
I have implemented something like this to handle any number sequence

https://dotnetfiddle.net/N8Oe9e

```csharp
	public static void Main()
	{
		var list = new List<int>
		{
			0,
			3,
			6,
			9,
			0
		};
		Console.WriteLine(hasSubsequences(list.ToArray()));
	}

	private static bool hasSubsequences(int[] vals)
	{
		var passwordValidator = new PasswordValidator(CheckTypes.DigitRepetition)
		{
			DigitRepetitionLength = 2
		};
		List<int> differences = new List<int>();
		for (int i = 0; i < vals.Length - 1; i++)
		{
			differences.Add(findDifference(vals[i + 1], vals[i]));
		}

		return !passwordValidator.Validate(string.Join<int>(",", differences));
	}

	private static int findDifference(int nr1, int nr2)
	{
		return nr1 - nr2;
	}
```

The above solution leverages this plugins `DigitRepetitionLength`, which is where the same difference is observed in repetition. This would indicate a sequence.
